import streamlit as st


def run():
    st.title("About Us!!!! :newspaper:")

    st.markdown("Welcome to **Time Based Invoicing**, where we are passionate about simplifying "
                "the invoicing process for professionals who value their time. Our "
                "journey began with a simple yet profound realization: the need for an "
                "intuitive, efficient, and customizable invoicing system tailored "
                "specifically for individuals who charge for their services based on "
                "time, reflecting a rate per hour. \n\n I.\n\n Our Vision and Mission At ["
                "Your"
                "App's Name], we envision a world where every professional—be it "
                "freelancers, consultants, creatives, or service providers—can focus on "
                "their craft without the burden of complex billing processes. Our mission"
                "is to empower individuals to accurately and effortlessly bill for their "
                "time, ensuring fair compensation for the value they bring to their "
                "clients. \n\nII.\n\n The Problem We Address Traditional invoicing systems "
                "often"
                "fall short when it comes to accommodating the unique needs of those who "
                "bill by the hour. Cumbersome interfaces, rigid structures, and generic "
                "features can create frustration and inefficiency. Recognizing this gap, "
                "we set out to create an invoicing solution that not only streamlines the"
                "billing process but also enhances the overall experience for time-based "
                "professionals.\n\nIII.\n\n Our Solution: **Time Based Invoicing**\n\nA.\n\n Intuitive "
                "Time"
                "Tracking:**Time Based Invoicing** features an intuitive time tracking system "
                "that allows you to effortlessly log and monitor billable hours. Whether "
                "you're on the go or working from your desk, our user-friendly interface "
                "ensures accurate timekeeping with just a few clicks.\n\nB.\n\n **Customizable "
                "Rate"
                "Structures:**\nWe understand that not all professionals charge the same rate"
                "for their time. Our app allows you to set customizable rate structures, "
                "accommodating different projects, clients, or types of services. This "
                "flexibility ensures that you are accurately compensated for the unique "
                "value you provide.\n\nC.\n\n **Effortless Invoicing:** Creating and sending "
                "invoices has never been easier. Time Based Invoicing automates the invoicing "
                "process, pulling in your logged hours and applying the corresponding "
                "rates. Customize your invoices with your branding, add detailed project "
                "descriptions, and send them to clients with confidence.\n\nD.\n\n Real-time "
                "Analytics:Gain insights into your work patterns and financial "
                "performance with our real-time analytics. Track your income, "
                "monitor outstanding payments, and make informed decisions to optimize "
                "your time and maximize your revenue.\n\nIV.\n\n Our Commitment to User "
                "Experience\n\nA.\n\n Simplicity and Accessibility:We believe in the power of "
                "simplicity. **Time Based Invoicing** is designed to be user-friendly, "
                "ensuring that even those unfamiliar with complex invoicing systems can "
                "navigate with ease. Access your account from any device, anywhere, "
                "and enjoy a seamless experience.\n\nB.\n\n Continuous Innovation:We are "
                "committed to staying at the forefront of technology. Our team regularly "
                "updates and enhances **Time Based Invoicing** to incorporate the latest "
                "features, security measures, and industry best practices. Your success "
                "is our motivation for continuous improvement.\n\nV.\n\n Security and "
                "PrivacyWe"
                "recognize the sensitivity of financial and time-related data. [Your "
                "App's Name] employs robust security measures to safeguard your "
                "information. Our commitment to privacy ensures that your data remains "
                "confidential, giving you the peace of mind to focus on what you do "
                "best.\n\nVI.\n\n Join Our Community\nA.\n\n User Support and Resources:Your "
                "success is"
                "our priority. Our dedicated support team is ready to assist you with any"
                "questions or issues. Additionally, access a wealth of resources, "
                "including tutorials, FAQs, and community forums, to maximize your "
                "experience with **Time Based Invoicing**.\n\nB.\n\n Feedback and Collaboration:We "
                "value"
                "your feedback. Share your insights, suggestions, and experiences with "
                "us. Your input fuels our commitment to continuous improvement. Let's "
                "grow together and shape the future of time-based billing.\n\nVII.\n\n Get "
                "Started with **Time Based Invoicing**Join the growing community of "
                "professionals who have embraced **Time Based Invoicing** as their preferred "
                "invoicing solution. Experience the freedom to focus on your work, "
                "confident that our system is working seamlessly in the background to "
                "ensure accurate and timely billing.Thank you for choosing [Your App's "
                "Name]. Let's redefine the way you bill for your time—because your time "
                "is valuable, and so is your success.")
